### ISSUE TITLE
testdata 6 ValueError in flow.is_redundant when k suboptimal

### ISSUE THREAD

**Issue by kkloste** [sgsmob/toboggan#3]
At this point `toboggan.py` correctly runs on all 6 testdata instances when groundtruth `k` is provided, and runs properly on instances 1-5 when no groundtruth is provided. For instance number 6, with no groundtruth provided, we get the following error:

```bash
❭ python3 toboggan.py testdata/toboggan_test.graph --indices 6
# No timeout set
# Running on instances 6
# No ground-truth found. Guessing parameter.
6 six_paths_10_20_30_40_100_100:5 with n = 6, m = 12, and k = ?: 
Traceback (most recent call last):
  File "toboggan.py", line 185, in <module>
    solution, k = find_opt_size(reduced, k, maxtime)
  File "toboggan.py", line 87, in find_opt_size
    solutions = solve(instance, silent=True)
  File "/home/hyunil/research/toboggan-dev/toboggan/guess_weight.py", line 98, in solve
    sol = solve_dp(instance, silent=True, guessed_weights=weights)
  File "/home/hyunil/research/toboggan-dev/toboggan/dp.py", line 115, in solve
    elif newconstr.is_redundant(newpaths):
  File "/home/hyunil/research/toboggan-dev/toboggan/flow.py", line 166, in is_redundant
    optres = linprog(c, A_ub, b_ub, A_eq, b_eq, bounds)
  File "/home/hyunil/anaconda3/lib/python3.6/site-packages/scipy/optimize/_linprog.py", line 993, in linprog
    bounds=bounds, callback=callback, **options)
  File "/home/hyunil/anaconda3/lib/python3.6/site-packages/scipy/optimize/_linprog.py", line 710, in _linprog_simplex
    raise ValueError(message)
ValueError: Invalid input for linprog with method = 'simplex'.  Lower bound 2 is greater than upper bound 2
```

**Comment by kkloste** [comment]
Update on interpretting the error: "lower bound 2" and "upper bound 2" do not mean that the values of the bounds are both 2 -- they refer to the second entries of the `bounds` variable here:
```python
# Bounds for flow values: at least 1, at most F-(t-1) (since non-zero)
bounds = self.instance.weight_bounds
optres = linprog(c, A_ub, b_ub, A_eq, b_eq, bounds)
```
Printing out `bounds` yields:
```python
[[  1  10]
[ 60  20]
[ 50  40]
[ 66 100]
[ 50 100]]
```
and the second row clearly has its inequality reversed.

Felix has suggested this is an early-out situation that should be caught with a `is_feasible` check on the weight-bounds.
I'm looking into this to confirm that the only time this situation arises (weight-bounds being infeasible) is if the number of paths is insufficient (or the input graph is otherwise unsolvable)

**Comment by kkloste** [comment]
@sgsmob and I combed over the weight-bounds computing function in flow.py and figured out that when computing the lower bounds, we divide by "i" instead of "i+1", and that was the source of the bug.
